[package]
name = "Keyfinitum"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
active-win-pos-rs = "0.8.4"
winapi = { version = "0.3", features = ["winuser", "hidpi", "hidusage", "hidsdi"] }
eframe = "0.22"
egui = "0.22"
